// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:json_annotation/src/json_serializable.dart' as prefix2;
import 'package:silverliningspodcasts/src/helpers/ignore.dart' as prefix3;
import 'package:silverliningspodcasts/src/helpers/reflector.dart' as prefix0;
import 'package:silverliningspodcasts/src/models/user.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 13, 14],
            const <int>[15, 16, 17, 18, 19, 6, 7, 8, 9, 10, 11, 12],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) =>
                  (id, userName, password, firstName, lastName, email) => b
                      ? prefix1.User(
                          id, userName, password, firstName, lastName, email)
                      : null,
              r'fromJson': (b) =>
                  (json) => b ? prefix1.User.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector, const prefix2.JsonSerializable()],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 33797, 0, const prefix0.Reflector(), -1, 1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(r'userName', 33797, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const []),
        r.VariableMirrorImpl(r'password', 33797, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const []),
        r.VariableMirrorImpl(r'firstName', 33797, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const []),
        r.VariableMirrorImpl(r'lastName', 33797, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const []),
        r.VariableMirrorImpl(r'email', 33797, 0, const prefix0.Reflector(), -1,
            2, 2, const <int>[], const []),
        r.MethodMirrorImpl(r'toJson', 4325378, 0, -1, 3, 4, null, const <int>[],
            const prefix0.Reflector(), const <Object>[prefix3.ignore]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 7),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 9),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 11),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 5, 12),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1, 2, 3, 4, 5], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r'fromJson',
            1,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[6],
            const prefix0.Reflector(),
            const <Object>[prefix3.ignore]),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 5, 5, const <int>[],
            const <int>[7], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null,
            const <int>[], const <int>[8], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 6, 6,
            const <int>[], const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'id', 32774, 13, const prefix0.Reflector(), -1,
            1, 1, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'userName', 32774, 13, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'password', 32774, 13, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'firstName',
            32774,
            13,
            const prefix0.Reflector(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'lastName', 32774, 13, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'email', 32774, 13, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'json', 16390, 14, const prefix0.Reflector(),
            null, null, null, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'other', 32774, 15, const prefix0.Reflector(),
            -1, 7, 7, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            17,
            const prefix0.Reflector(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.User,
        int,
        String,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        bool,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'id': (dynamic instance) => instance.id,
        r'userName': (dynamic instance) => instance.userName,
        r'password': (dynamic instance) => instance.password,
        r'firstName': (dynamic instance) => instance.firstName,
        r'lastName': (dynamic instance) => instance.lastName,
        r'email': (dynamic instance) => instance.email
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
